name: Build a beta

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create and Push Tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          DATE=$(date +'%Y%m%d-%H%M')
          TAG="v$VERSION-$DATE"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git tag $TAG
          git push origin $TAG

      - name: Install deps
        run: npm install --legacy-peer-deps || true

      - name: Prebuild Android
        run: npx expo prebuild --platform android --clean

      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/release.keystore

      - name: Calculate Android Version Code
        run: |
          VERSION_CODE=$(node -e "
            const version = require('./package.json').version;
            const cleanVersion = parseInt(version.replace(/\./g, ''));
            const runNumber = parseInt(process.env.GITHUB_RUN_NUMBER || '0');
            console.log(cleanVersion * 100000 + runNumber);
          ")
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "Computed VERSION_CODE: $VERSION_CODE"

      - name: Configure Gradle
        run: |
          chmod +x android/gradlew
          echo "org.gradle.jvmargs=-Xmx6144m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError" >> android/gradle.properties
          echo "android.enable16KbPageSizes=true" >> android/gradle.properties

      - name: Create secrets.json
        run: |
          echo '{
            "APP_KEY": "${{ secrets.COUNTLY_APP_KEY }}",
            "SALT": "${{ secrets.COUNTLY_SALT }}",
            "SERVER_URL": "${{ secrets.COUNTLY_SERVER_URL }}"
          }' > secrets.json

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon

      - name: Build AAB
        run: |
          cd android
          ./gradlew bundleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/*.aab
